
trigger:
- main
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '6.x'
    checkLatest: true
- task: AzureFunctionApp@2
  inputs:
    connectedServiceNameARM: 'Primer Azure subscription(b620a3d7-662f-4cf9-adc4-911996c0a2ed)'
    appType: 'functionAppLinux'
    appName: 'azurefunction-app'
    deployToSlotOrASE: true
    resourceGroupName: 'automation-azure'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'NODE|16'
    deploymentMethod: 'auto'
    environmentVariables: |
      USER=$(USER)
      PASSWORD=$(PASSWORD)
      PORT=$(PORT)
  displayName: 'Deploy to Function App'
