# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureFunctionApp@1
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/dist'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- script:
    azureSubscription: 'Primer Azure subscription'
    appType: 'functionAppLinux'
    appName: 'CVAP Function App'
    package: '$(System.DefaultWorkingDirectory)/CVAPFunctionApp.zip'
    runtimeStack: 'NODE|14-lts'
    startUpCommand: 'npm run start'
    environmentVariables: |
      DB_HOST=$(DB_HOST)
      DB_PORT=$(DB_PORT)
      DB_USERNAME=$(DB_USERNAME)
      DB_PASSWORD=$(DB_PASSWORD)
      DB_DATABASE=$(DB_DATABASE)
  displayName: 'Deploy to Function App'
